dependencies:
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::python=3.10
  - conda-forge::hcipy
  - conda-forge::jupyter
  - conda-forge::asdf
  - pip:
      - matplotlib
      - imageio
